version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: techstars_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-techstars}
      POSTGRES_USER: ${POSTGRES_USER:-techstars}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-techstars}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-techstars} -d ${POSTGRES_DB:-techstars}"]
      interval: 5s
      timeout: 5s
      retries: 10

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: techstars_selenium
    shm_size: 2g
    environment:
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_SESSION_TIMEOUT: 300
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4444/status | grep -q 'ready'"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techstars_app
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-techstars}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-techstars}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-techstars}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SELENIUM_REMOTE_URL: http://selenium:4444/
      SELENIUM_SCRIPT_TIMEOUT_SEC: 60
      JAVA_OPTS: "-Xms256m -Xmx768m"
      DUMPS_DIR: /data
    ports:
      - "8080:8080"
    volumes:
      - ./dumps:/data

volumes:
  db_data:
